/**
 * AUTO-GENERATED by scripts/generate-roc-waves-barrel.mjs — do not edit by hand.
 * Re-run: node scripts/generate-roc-waves-barrel.mjs
 * Attribution: Veritas Worldwide only.
 */

import { ROC_WAVE3_CLAIMS } from './recordOfJesusChristWave3'
import { ROC_WAVE4_CLAIMS } from './recordOfJesusChristWave4'
import { ROC_WAVE5_CLAIMS } from './recordOfJesusChristWave5'
import { ROC_WAVE6_CLAIMS } from './recordOfJesusChristWave6'
import { ROC_WAVE7_CLAIMS } from './recordOfJesusChristWave7'
import { ROC_WAVE8_CLAIMS } from './recordOfJesusChristWave8'
import { ROC_WAVE9_CLAIMS } from './recordOfJesusChristWave9'
import { ROC_WAVE10_CLAIMS } from './recordOfJesusChristWave10'
import { ROC_WAVE11_CLAIMS } from './recordOfJesusChristWave11'
import { ROC_WAVE12_CLAIMS } from './recordOfJesusChristWave12'
import { ROC_WAVE13_CLAIMS } from './recordOfJesusChristWave13'
import { ROC_WAVE14_CLAIMS } from './recordOfJesusChristWave14'
import { ROC_WAVE15_CLAIMS } from './recordOfJesusChristWave15'
import { ROC_WAVE16_CLAIMS } from './recordOfJesusChristWave16'
import { ROC_WAVE17_CLAIMS } from './recordOfJesusChristWave17'
import { ROC_WAVE18_CLAIMS } from './recordOfJesusChristWave18'
import { ROC_WAVE19_CLAIMS } from './recordOfJesusChristWave19'
import { ROC_WAVE20_CLAIMS } from './recordOfJesusChristWave20'
import { ROC_WAVE21_CLAIMS } from './recordOfJesusChristWave21'
import { ROC_WAVE22_CLAIMS } from './recordOfJesusChristWave22'
import { ROC_WAVE23_CLAIMS } from './recordOfJesusChristWave23'
import { ROC_WAVE24_CLAIMS } from './recordOfJesusChristWave24'
import { ROC_WAVE25_CLAIMS } from './recordOfJesusChristWave25'
import { ROC_WAVE26_CLAIMS } from './recordOfJesusChristWave26'
import { ROC_WAVE27_CLAIMS } from './recordOfJesusChristWave27'
import { ROC_WAVE28_CLAIMS } from './recordOfJesusChristWave28'
import { ROC_WAVE29_CLAIMS } from './recordOfJesusChristWave29'
import { ROC_WAVE30_CLAIMS } from './recordOfJesusChristWave30'
import { ROC_WAVE31_CLAIMS } from './recordOfJesusChristWave31'
import { ROC_WAVE32_CLAIMS } from './recordOfJesusChristWave32'
import { ROC_WAVE33_CLAIMS } from './recordOfJesusChristWave33'
import { ROC_WAVE34_CLAIMS } from './recordOfJesusChristWave34'
import { ROC_WAVE35_CLAIMS } from './recordOfJesusChristWave35'
import { ROC_WAVE36_CLAIMS } from './recordOfJesusChristWave36'
import { ROC_WAVE37_CLAIMS } from './recordOfJesusChristWave37'
import { ROC_WAVE38_CLAIMS } from './recordOfJesusChristWave38'
import { ROC_WAVE39_CLAIMS } from './recordOfJesusChristWave39'
import { ROC_WAVE40_CLAIMS } from './recordOfJesusChristWave40'
import { ROC_WAVE41_CLAIMS } from './recordOfJesusChristWave41'
import { ROC_WAVE42_CLAIMS } from './recordOfJesusChristWave42'
import { ROC_WAVE43_CLAIMS } from './recordOfJesusChristWave43'
import { ROC_WAVE44_CLAIMS } from './recordOfJesusChristWave44'
import { ROC_WAVE45_CLAIMS } from './recordOfJesusChristWave45'
import { ROC_WAVE46_CLAIMS } from './recordOfJesusChristWave46'
import { ROC_WAVE47_CLAIMS } from './recordOfJesusChristWave47'
import { ROC_WAVE48_CLAIMS } from './recordOfJesusChristWave48'
import { ROC_WAVE49_CLAIMS } from './recordOfJesusChristWave49'
import { ROC_WAVE50_CLAIMS } from './recordOfJesusChristWave50'
import { ROC_WAVE51_CLAIMS } from './recordOfJesusChristWave51'
import { ROC_WAVE52_CLAIMS } from './recordOfJesusChristWave52'
import { ROC_WAVE53_CLAIMS } from './recordOfJesusChristWave53'
import { ROC_WAVE54_CLAIMS } from './recordOfJesusChristWave54'
import { ROC_WAVE55_CLAIMS } from './recordOfJesusChristWave55'
import { ROC_WAVE56_CLAIMS } from './recordOfJesusChristWave56'
import { ROC_WAVE57_CLAIMS } from './recordOfJesusChristWave57'
import { ROC_WAVE58_CLAIMS } from './recordOfJesusChristWave58'
import { ROC_WAVE59_CLAIMS } from './recordOfJesusChristWave59'
import { ROC_WAVE60_CLAIMS } from './recordOfJesusChristWave60'
import { ROC_WAVE61_CLAIMS } from './recordOfJesusChristWave61'
import { ROC_WAVE62_CLAIMS } from './recordOfJesusChristWave62'
import { ROC_WAVE63_CLAIMS } from './recordOfJesusChristWave63'
import { ROC_WAVE64_CLAIMS } from './recordOfJesusChristWave64'
import { ROC_WAVE65_CLAIMS } from './recordOfJesusChristWave65'
import { ROC_WAVE66_CLAIMS } from './recordOfJesusChristWave66'

export const ROC_WAVE_CLAIM_MAPS = [
  ROC_WAVE3_CLAIMS,
  ROC_WAVE4_CLAIMS,
  ROC_WAVE5_CLAIMS,
  ROC_WAVE6_CLAIMS,
  ROC_WAVE7_CLAIMS,
  ROC_WAVE8_CLAIMS,
  ROC_WAVE9_CLAIMS,
  ROC_WAVE10_CLAIMS,
  ROC_WAVE11_CLAIMS,
  ROC_WAVE12_CLAIMS,
  ROC_WAVE13_CLAIMS,
  ROC_WAVE14_CLAIMS,
  ROC_WAVE15_CLAIMS,
  ROC_WAVE16_CLAIMS,
  ROC_WAVE17_CLAIMS,
  ROC_WAVE18_CLAIMS,
  ROC_WAVE19_CLAIMS,
  ROC_WAVE20_CLAIMS,
  ROC_WAVE21_CLAIMS,
  ROC_WAVE22_CLAIMS,
  ROC_WAVE23_CLAIMS,
  ROC_WAVE24_CLAIMS,
  ROC_WAVE25_CLAIMS,
  ROC_WAVE26_CLAIMS,
  ROC_WAVE27_CLAIMS,
  ROC_WAVE28_CLAIMS,
  ROC_WAVE29_CLAIMS,
  ROC_WAVE30_CLAIMS,
  ROC_WAVE31_CLAIMS,
  ROC_WAVE32_CLAIMS,
  ROC_WAVE33_CLAIMS,
  ROC_WAVE34_CLAIMS,
  ROC_WAVE35_CLAIMS,
  ROC_WAVE36_CLAIMS,
  ROC_WAVE37_CLAIMS,
  ROC_WAVE38_CLAIMS,
  ROC_WAVE39_CLAIMS,
  ROC_WAVE40_CLAIMS,
  ROC_WAVE41_CLAIMS,
  ROC_WAVE42_CLAIMS,
  ROC_WAVE43_CLAIMS,
  ROC_WAVE44_CLAIMS,
  ROC_WAVE45_CLAIMS,
  ROC_WAVE46_CLAIMS,
  ROC_WAVE47_CLAIMS,
  ROC_WAVE48_CLAIMS,
  ROC_WAVE49_CLAIMS,
  ROC_WAVE50_CLAIMS,
  ROC_WAVE51_CLAIMS,
  ROC_WAVE52_CLAIMS,
  ROC_WAVE53_CLAIMS,
  ROC_WAVE54_CLAIMS,
  ROC_WAVE55_CLAIMS,
  ROC_WAVE56_CLAIMS,
  ROC_WAVE57_CLAIMS,
  ROC_WAVE58_CLAIMS,
  ROC_WAVE59_CLAIMS,
  ROC_WAVE60_CLAIMS,
  ROC_WAVE61_CLAIMS,
  ROC_WAVE62_CLAIMS,
  ROC_WAVE63_CLAIMS,
  ROC_WAVE64_CLAIMS,
  ROC_WAVE65_CLAIMS,
  ROC_WAVE66_CLAIMS,
] as const

export const ROC_WAVE_NUMBERS = [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66] as const

